"""Character sets for training."""

# Auto-discovered distinct characters (pairwise embedding similarity < 0.80)
# Generated by discover_distinct.py from 1215 Unicode candidates
DISTINCT = (
    " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFG"
    "HIJKLMNOPRSTUVWXYZ[\\]^_`abcdefghijklmnop"
    "qrstuvwxyz{|}~¡¢£¤¥¦§©ª«¬®¯°±²³µ¶·¸¹º»¼½"
    "¾¿Æ×ØÞßâæçð÷ø─━┃┄┅┆┇┉┊┋┌┍┎┏┐┓└┖┗┘┙├┝┠┣┤┧"
    "┨┬┭┮┳┴┷┼╅╊╏═║╒╓╔╕╖╗╘╙╚╛╜╝╟╡╣╤╥╦╧╩╪╫╬╭╯╰╱"
    "╳╵╶╷╸╹╺╻╽▀▁▂▃▄▅▆▇█▉▊▋▍▎▏▐░▒▓▔▕▖▗▘▙▚▛▜▝▞▟"
    "■□▣▤▥▩▪▫▬▭▮▯▲△▴▵▶▷▸▹►▻▼▽▾▿◀◁◂◃◅◆◇◉◊○◌◍◎●"
    "◐◑◒◓◔◕◖◗◘◙◚◛◜◝◞◟◠◡◢◣◤◥◦◧◨◩◪◫◬◭◮◯◰◲◳◴◵◶◷◸"
    "◹◺◻◼◽◿☀☁☂☃★☆☇☈☉☊☋☌☍☎☏☐☑☒☓☔☕☖☗☘☙☚☛☝☟☠☡☢☣☤"
    "☥☦☧☨☩☪☫☬☭☮☯☰☸☺☻☽☾☿♀♁♂♃♄♅♆♇♈♉♊♋♌♍♎♏♐♑♓♔♕♖"
    "♗♘♙♚♛♜♝♞♟♠♡♣♥♦♧♨♩♪♫♬♭♮♯♰♱♲♳♴♶♸♺♻♼♽♾♿⚀⚁⚃⚅"
    "⚆⚈⚊⚐⚑⚒⚓⚔⚕⚖⚗⚘⚙⚚⚜⚠⚰⚱✁✃✄✆✇✈✉✌✍✎✏✐✑✒✓✕✖✗✘✙✚✛"
    "✜✝✞✟✠✡✢✣✥✩✪✫✬✭✮✰✱✲✴✵✶✸✺✻✽✾✿❀❁❂❃❄❅❆❈❉❋❍❏❐"
    "❑❒❙❚❜❞❡❢❤❥❧❨❩❪❭❮❯❰❱❲❳❴❵➔➘➙➚➝➢➣➤➧➩➪➫➬➮➯➱➲"
    "➴➷➺"
)


def get_charset(name: str) -> list[str]:
    if name == 'distinct':
        return list(DISTINCT)
    elif name == 'ascii':
        return [chr(i) for i in range(0x20, 0x7F)]
    elif name == 'blocks':
        return [chr(i) for i in range(0x2580, 0x25A0)]
    else:
        return list(DISTINCT)  # default to distinct


if __name__ == '__main__':
    print(f"Distinct: {len(DISTINCT)} chars")
